# Generated by Django 4.1.5 on 2023-01-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=128)),
                ("temperature", models.IntegerField()),
                ("feels_like", models.IntegerField()),
                ("humidity", models.IntegerField()),
            ],
        ),
    ]
