# Generated by Django 4.0.6 on 2023-01-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registros',
            old_name='sens_temperature',
            new_name='feels_like',
        ),
    ]
